version: '3.7'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
    volumes:
      - ./uploads:/app/uploads
    environment:
      DB_HOST: pg
    networks:
      - backend
    links:
      - pg
    depends_on:
      - pg
  pg:
    image: postgres
    container_name: pg
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photo_identity
    ports:
      - '5432:5432'
    networks:
      - backend

networks:
  backend:
    driver: bridge
